/*
 * This file is generated by jOOQ.
 */
package com.example.demo.models;


import java.io.Serializable;
import java.math.BigDecimal;
import java.time.OffsetDateTime;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;


/**
 * 書本資料表，用於儲存書本的基本資訊
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Entity
@Table(
    name = "book",
    schema = "public",
    uniqueConstraints = {
        @UniqueConstraint(name = "uk_isbn", columnNames = { "isbn" })
    },
    indexes = {
        @Index(name = "idx_author", columnList = "author ASC"),
        @Index(name = "idx_publish_year", columnList = "publish_year ASC")
    }
)
public class Book implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private String title;
    private String author;
    private String isbn;
    private Integer publishYear;
    private BigDecimal price;
    private OffsetDateTime createdAt;
    private OffsetDateTime updatedAt;

    public Book() {}

    public Book(Book value) {
        this.id = value.id;
        this.title = value.title;
        this.author = value.author;
        this.isbn = value.isbn;
        this.publishYear = value.publishYear;
        this.price = value.price;
        this.createdAt = value.createdAt;
        this.updatedAt = value.updatedAt;
    }

    public Book(
        Integer id,
        String title,
        String author,
        String isbn,
        Integer publishYear,
        BigDecimal price,
        OffsetDateTime createdAt,
        OffsetDateTime updatedAt
    ) {
        this.id = id;
        this.title = title;
        this.author = author;
        this.isbn = isbn;
        this.publishYear = publishYear;
        this.price = price;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    /**
     * Getter for <code>public.book.id</code>. 書本 ID，使用 SERIAL 自動產生遞增值
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false)
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.book.id</code>. 書本 ID，使用 SERIAL 自動產生遞增值
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.book.title</code>. 書名，必填，最大長度 255 字元
     */
    @Column(name = "title", nullable = false, length = 255)
    @NotNull
    @Size(max = 255)
    public String getTitle() {
        return this.title;
    }

    /**
     * Setter for <code>public.book.title</code>. 書名，必填，最大長度 255 字元
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * Getter for <code>public.book.author</code>. 作者名稱，必填，最大長度 100 字元
     */
    @Column(name = "author", nullable = false, length = 100)
    @NotNull
    @Size(max = 100)
    public String getAuthor() {
        return this.author;
    }

    /**
     * Setter for <code>public.book.author</code>. 作者名稱，必填，最大長度 100 字元
     */
    public void setAuthor(String author) {
        this.author = author;
    }

    /**
     * Getter for <code>public.book.isbn</code>. 國際標準書號，必填，固定 13 位數
     */
    @Column(name = "isbn", nullable = false, length = 13)
    @NotNull
    @Size(max = 13)
    public String getIsbn() {
        return this.isbn;
    }

    /**
     * Setter for <code>public.book.isbn</code>. 國際標準書號，必填，固定 13 位數
     */
    public void setIsbn(String isbn) {
        this.isbn = isbn;
    }

    /**
     * Getter for <code>public.book.publish_year</code>. 出版年份，可為空
     */
    @Column(name = "publish_year")
    public Integer getPublishYear() {
        return this.publishYear;
    }

    /**
     * Setter for <code>public.book.publish_year</code>. 出版年份，可為空
     */
    public void setPublishYear(Integer publishYear) {
        this.publishYear = publishYear;
    }

    /**
     * Getter for <code>public.book.price</code>. 價格，可為空，最多 10 位數，小數點後 2 位
     */
    @Column(name = "price", precision = 10, scale = 2)
    public BigDecimal getPrice() {
        return this.price;
    }

    /**
     * Setter for <code>public.book.price</code>. 價格，可為空，最多 10 位數，小數點後 2 位
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * Getter for <code>public.book.created_at</code>. 建立時間，自動填入當前時間
     */
    @Column(name = "created_at", precision = 6)
    public OffsetDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>public.book.created_at</code>. 建立時間，自動填入當前時間
     */
    public void setCreatedAt(OffsetDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * Getter for <code>public.book.updated_at</code>. 更新時間，自動填入當前時間
     */
    @Column(name = "updated_at", precision = 6)
    public OffsetDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    /**
     * Setter for <code>public.book.updated_at</code>. 更新時間，自動填入當前時間
     */
    public void setUpdatedAt(OffsetDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }
}
