db.url: jdbc:postgresql://localhost:5432/mydatabase
db.username: myuser
db.password: secret
redis.host: localhost

spring:
  main:
    banner-mode: console
  jpa:
    show-sql: true # 本地開發顯示 SQL 語句，便於除錯
    properties:
      hibernate:
        format_sql: true # 格式化 SQL 輸出

springdoc:
  api-docs:
    enabled: true # 啟用 springdoc-openapi 端點
  show-actuator: true # 顯示 actuator 端點

management:
  opentelemetry:
    resource-attributes:
      service.version: ${spring.application.version}
      execution.environment: "local"
  endpoints:
    web:
      exposure:
        include: "*" # 開發環境開放所有端點
  tracing:
    sampling:
      probability: 1.0
  info:
    git:
      mode: full
  otlp: # 本地開發啟用 OTLP，方便觀察監控數據
    metrics:
      export:
        enabled: true
    tracing:
      export:
        enabled: true
    logging:
      export:
        enabled: true
  endpoint:
    health:
      show-details: always
  
server:
  error:
    include-message: always
    include-binding-errors: always

# 本地開發日誌配置
logging:
  level:
    root: info
    com.example.demo: debug # 應用程式詳細日誌
    org.springframework.cache: debug # 快取操作日誌
    org.springframework.web: debug # Web 請求日誌
    org.hibernate.SQL: debug # SQL 語句日誌
    org.hibernate.type.descriptor.sql.BasicBinder: trace # SQL 參數日誌


