# 資料庫連線設定 (SIT 環境通常使用獨立的測試資料庫)
db.url: jdbc:postgresql://localhost:5432/mydatabase
db.username: myuser
db.password: secret
redis.host: localhost
otlp.metrics.endpoint: http://sit-otel-collector:4318/v1/metrics
otlp.traces.endpoint: http://sit-otel-collector:4318/v1/traces
otlp.logs.endpoint: http://sit-otel-collector:4318/v1/logs

spring:
  main:
    banner-mode: off # SIT 環境關閉 banner 減少日誌雜訊
  data:
    redis:
      timeout: 3000ms # SIT 環境較寬鬆的逾時設定

springdoc:
  show-actuator: true # SIT 環境顯示 actuator 端點
  api-docs:
    enabled: true # 啟用 Swagger UI 方便 API 測試

management:
  opentelemetry:
    resource-attributes:
      service.version: ${spring.application.version}
      execution.environment: "sit"
  endpoints:
    web:
      exposure:
        include: "*" # sit 環境開放所有端點
  tracing:
    sampling:
      probability: 1.0 # SIT 環境需要完整追蹤以便問題排查
  info:
    git:
      mode: full # 顯示完整的 Git 資訊以便版本追蹤
  endpoint:
    health:
      show-details: always # 顯示詳細健康狀態
  otlp: # sit 增加紀錄的收集
    metrics:
      export:
        enabled: true
        step: 10s
    tracing:
      export:
        enabled: true
    logging:
      export:
        enabled: true

server:
  error: # SIT 環境顯示詳細錯誤以便測試
    include-message: always
    include-binding-errors: always

logging:
  level:
    root: info
    com.example.demo: debug # SIT 環境啟用詳細日誌以便問題排查
    org.springframework.web: info
    org.springframework.transaction: debug # 監控事務行為
    org.springframework.data.jpa: debug # 監控 JPA 查詢
