spring:
  main:
    banner-mode: console
  # 資料庫連線設定
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: myuser
    password: secret
  data:
    redis:
      host: localhost
      port: 6379

springdoc:
  show-actuator: true # 開發環境顯示 actuator 端點
  api-docs:
    enabled: true # 啟用 Swagger UI

logging:
  level:
    root: info
    com.example.demo: debug
    org.springframework.web: debug

management:
  opentelemetry:
    resource-attributes:
      deployment.environment: "ut"
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  otlp:
    metrics:
      export:
        enabled: true
        url: http://localhost:4318/v1/metrics
        step: 10s
    tracing:
      export:
        enabled: true
      endpoint: http://localhost:4318/v1/traces
    logging:
      export:
        enabled: true
      endpoint: http://localhost:4318/v1/logs

server:
  error:
    include-message: always
    include-binding-errors: always